const WHATSAPP_COUNTRY_CODE = "32";
const WHATSAPP_NUMBER = "484706809";
const WHATSAPP_MESSAGE = "Hallo Dirk, ik heb interesse in een eenvoudige website via DirkWeb.";
function buildWhatsAppUrl(){return `https://wa.me/${WHATSAPP_COUNTRY_CODE}${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`}
function initWhatsAppLinks(){document.querySelectorAll(".js-whatsapp").forEach((link)=>{link.href=buildWhatsAppUrl();link.target="_blank";link.rel="noopener noreferrer"})}
function initMobileNavigation(){const toggle=document.querySelector(".nav-toggle"),nav=document.querySelector(".site-nav");if(!toggle||!nav)return;toggle.addEventListener("click",()=>{const open=nav.classList.toggle("is-open");toggle.setAttribute("aria-expanded",String(open))});nav.addEventListener("click",e=>{if(e.target instanceof HTMLAnchorElement){nav.classList.remove("is-open");toggle.setAttribute("aria-expanded","false")}});document.addEventListener("keydown",e=>{if(e.key==="Escape"){nav.classList.remove("is-open");toggle.setAttribute("aria-expanded","false")}})}
function initCopyrightYear(){document.querySelectorAll(".js-year").forEach(el=>{el.textContent=new Date().getFullYear()})}
function initActiveNavState(){const current=window.location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".site-nav a").forEach(link=>{if(link.getAttribute("href")===current){link.classList.add("is-active");link.setAttribute("aria-current","page")}})}
function encodeFormData(form){return new URLSearchParams(new FormData(form)).toString()}
function initNetlifyFormMessage(){const form=document.querySelector(".js-contact-form");if(!form)return;const msg=form.querySelector(".js-form-success"),button=form.querySelector('button[type="submit"]'),original=button?button.textContent:"";form.addEventListener("submit",e=>{e.preventDefault();if(msg){msg.hidden=true;msg.textContent="Bedankt voor je bericht. DirkWeb neemt zo snel mogelijk contact met je op."}if(button){button.disabled=true;button.textContent="Bezig met versturen..."}fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:encodeFormData(form)}).then(r=>{if(!r.ok)throw new Error("send failed");form.reset();if(msg)msg.hidden=false}).catch(()=>{if(msg){msg.hidden=false;msg.textContent="Er ging iets mis bij het versturen. Probeer het later opnieuw of neem telefonisch contact op."}}).finally(()=>{if(button){button.disabled=false;button.textContent=original||"Verstuur je vraag"}})})}
function createImageFallback(image){const fallback=document.createElement("div");fallback.className="image-fallback";fallback.setAttribute("role","img");fallback.setAttribute("aria-label",image.alt||"Afbeelding niet beschikbaar");fallback.textContent="DirkWeb";image.replaceWith(fallback)}
function initImageFallbacks(){document.querySelectorAll("img[data-fallback='true']").forEach(image=>{image.addEventListener("error",()=>createImageFallback(image),{once:true});if(image.complete&&image.naturalWidth===0)createImageFallback(image)})}
document.addEventListener("DOMContentLoaded",()=>{initWhatsAppLinks();initMobileNavigation();initCopyrightYear();initActiveNavState();initNetlifyFormMessage();initImageFallbacks()});
